name: AliyunDrive Clean Task

on:
  schedule:
    - cron: '20 17 * * *'
  workflow_dispatch:

jobs:
  aliyundrive-clean:
    runs-on: ubuntu-latest
    env: 
      ALIYUNPAN_VERSION: 0.2.8
    steps:
    - name: Download aliyunpan command
      run: |
        wget https://github.com/tickstep/aliyunpan/releases/download/v$ALIYUNPAN_VERSION/aliyunpan-v$ALIYUNPAN_VERSION-linux-amd64.zip
        unzip aliyunpan-v$ALIYUNPAN_VERSION-linux-amd64.zip
        mv aliyunpan-v$ALIYUNPAN_VERSION-linux-amd64 aliyunpan
        ./aliyunpan/aliyunpan help

    - name: Delete the Xiaoya folder
      run: |
        ./aliyunpan/aliyunpan login -RefreshToken=${{ secrets.ALIYUNPAN_TOKEN }}
        ./aliyunpan/aliyunpan drive 678415103
        ./aliyunpan/aliyunpan ll
        ./aliyunpan/aliyunpan recycle delete -all
