name: AliyunDrive Clean Task

on:
  schedule:
    - cron: '20 17 * * *'
  workflow_dispatch:

jobs:
  aliyundrive-clean:
    runs-on: ubuntu-latest
    steps:
    - name: Download aliyunpan command
      run: |
        wget https://github.com/tickstep/aliyunpan/releases/download/v${{ env.ALIYUNPAN_VERSION }}/aliyunpan-v${{ env.ALIYUNPAN_VERSION }}-linux-amd64.zip
        unzip aliyunpan-v${{ env.ALIYUNPAN_VERSION }}-linux-amd64.zip
        mv aliyunpan-v${{ env.ALIYUNPAN_VERSION }}-linux-amd64 aliyunpan
        ./aliyunpan/aliyunpan help

    - name: Delete the Xiaoya folder
      run: |
        ./aliyunpan/aliyunpan login -RefreshToken=${{ secrets.ALIYUNPAN_TOKEN }}
        ./aliyunpan/aliyunpan pwd
        ./aliyunpan/aliyunpan ls
        ./aliyunpan/aliyunpan drive
        ./aliyunpan/aliyunpan help recycle
